// © Broadcom. All Rights Reserved.
// The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: MPL-2.0

package kubernetes

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var MetadataDataSourceSchema = schema.SingleNestedAttribute{
	Computed:    true,
	Description: "Standard Kubernetes object metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
	Attributes: map[string]schema.Attribute{
		"name": schema.StringAttribute{
			Computed:    true,
			Description: "Name of the object",
		},
		"generate_name": schema.StringAttribute{
			Computed:    true,
			Description: "GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the server will only assign a name if the Name field is empty. This value will be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.",
		},
		"namespace": schema.StringAttribute{
			Computed:    true,
			Description: "Namespace of the object",
		},
		"uid": schema.StringAttribute{
			Computed:    true,
			Description: "Unique identifier for the object, generated by the server on creation and immutable thereafter",
		},
		"resource_version": schema.StringAttribute{
			Computed:    true,
			Description: "Opaque version string used by clients to detect when the object has changed",
		},
		"generation": schema.Int64Attribute{
			Computed:    true,
			Description: "Sequence number representing the current generation of the desired state; incremented on every spec change",
		},
		"creation_timestamp": schema.StringAttribute{
			Computed:    true,
			Description: "RFC3339 timestamp recording when the object was created",
		},
		"deletion_timestamp": schema.StringAttribute{
			Computed:    true,
			Description: "RFC3339 timestamp when graceful deletion was requested; null when the object is not being deleted",
		},
		"deletion_grace_period_seconds": schema.Int64Attribute{
			Computed:    true,
			Description: "Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened.",
		},
		"labels": schema.MapAttribute{
			Computed:    true,
			ElementType: types.StringType,
			Description: "Map of string keys and values used to organize and categorize the object",
		},
		"annotations": schema.MapAttribute{
			Computed:    true,
			ElementType: types.StringType,
			Description: "Unstructured key-value pairs set by external tools to store and retrieve arbitrary metadata",
		},
		"owner_references": schema.SetNestedAttribute{
			Computed:    true,
			Description: "Objects that own this object; this object will be garbage-collected when all owners are deleted",
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"api_version": schema.StringAttribute{
						Computed:    true,
						Description: "API version of the owner object",
					},
					"kind": schema.StringAttribute{
						Computed:    true,
						Description: "Kind of the owner object",
					},
					"name": schema.StringAttribute{
						Computed:    true,
						Description: "Name of the owner object",
					},
					"uid": schema.StringAttribute{
						Computed:    true,
						Description: "UID of the owner object",
					},
					"controller": schema.BoolAttribute{
						Computed:    true,
						Description: "Whether this owner is the managing controller for the object",
					},
					"block_owner_deletion": schema.BoolAttribute{
						Computed:    true,
						Description: "Whether the owner's deletion should be blocked until this object is also deleted",
					},
				},
			},
		},
		"finalizers": schema.SetAttribute{
			Computed:    true,
			ElementType: types.StringType,
			Description: "Finalizers that must be empty before the object is removed from the registry",
		},
	},
}
