name: check-docs
on:
  push:
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'

permissions:
  contents: read

jobs:
  build:
    name: Check Documentation
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:

    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0  # Required to have tag information available

    - name: Install Terraform
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

    - name: Setup Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: 'go.mod'

    - name: Get latest released version
      run: echo "PROVIDER_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Check HCL
      run: make hclcheck
